import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';

interface InvoiceData {
  invoiceNumber: string;
  createdAt: Date | string;
  dueDate: Date | string;
  paidDate?: Date | string | null;
  status: string;
  client: { name: string; email?: string | null; phone?: string | null; address?: string | null };
  user: { name: string; businessName?: string | null; email: string; phone?: string | null };
  items: { description: string; quantity: number; unitPrice: unknown; total: unknown }[];
  subtotal: unknown;
  taxRate: unknown;
  taxAmount: unknown;
  total: unknown;
  notes?: string | null;
}

export function generateInvoicePDF(invoice: InvoiceData): PassThrough {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const stream = new PassThrough();
  doc.pipe(stream);

  const fmt = (v: unknown) => `$${Number(v).toFixed(2)}`;
  const fmtDate = (d: Date | string) => new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Header
  doc.fontSize(24).font('Helvetica-Bold').text('INVOICE', 50, 50);
  doc.fontSize(10).font('Helvetica').fillColor('#666666');
  doc.text(invoice.invoiceNumber, 50, 80);
  doc.text(`Status: ${invoice.status}`, 50, 95);

  // From (right side)
  const rightX = 350;
  doc.fillColor('#000000').font('Helvetica-Bold').fontSize(10).text('From:', rightX, 50);
  doc.font('Helvetica').fontSize(9).fillColor('#333333');
  doc.text(invoice.user.businessName || invoice.user.name, rightX, 65);
  doc.text(invoice.user.email, rightX, 78);
  if (invoice.user.phone) doc.text(invoice.user.phone, rightX, 91);

  // Bill To
  doc.fillColor('#000000').font('Helvetica-Bold').fontSize(10).text('Bill To:', 50, 130);
  doc.font('Helvetica').fontSize(9).fillColor('#333333');
  let billY = 145;
  doc.text(invoice.client.name, 50, billY);
  billY += 13;
  if (invoice.client.email) { doc.text(invoice.client.email, 50, billY); billY += 13; }
  if (invoice.client.phone) { doc.text(invoice.client.phone, 50, billY); billY += 13; }
  if (invoice.client.address) { doc.text(invoice.client.address, 50, billY); billY += 13; }

  // Dates (right side)
  doc.fillColor('#000000').font('Helvetica-Bold').fontSize(9).text('Date:', rightX, 130);
  doc.font('Helvetica').text(fmtDate(invoice.createdAt), rightX + 60, 130);
  doc.font('Helvetica-Bold').text('Due Date:', rightX, 145);
  doc.font('Helvetica').text(fmtDate(invoice.dueDate), rightX + 60, 145);
  if (invoice.paidDate) {
    doc.font('Helvetica-Bold').text('Paid:', rightX, 160);
    doc.font('Helvetica').text(fmtDate(invoice.paidDate), rightX + 60, 160);
  }

  // Table header
  const tableTop = 210;
  doc.fillColor('#4f46e5');
  doc.rect(50, tableTop, 495, 25).fill();
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(9);
  doc.text('Description', 60, tableTop + 7, { width: 230 });
  doc.text('Qty', 300, tableTop + 7, { width: 50, align: 'right' });
  doc.text('Unit Price', 360, tableTop + 7, { width: 80, align: 'right' });
  doc.text('Total', 450, tableTop + 7, { width: 85, align: 'right' });

  // Table rows
  let rowY = tableTop + 30;
  doc.font('Helvetica').fontSize(9).fillColor('#333333');
  invoice.items.forEach((item, i) => {
    const bg = i % 2 === 0 ? '#f9fafb' : '#ffffff';
    doc.fillColor(bg).rect(50, rowY - 5, 495, 22).fill();
    doc.fillColor('#333333');
    doc.text(item.description, 60, rowY, { width: 230 });
    doc.text(String(item.quantity), 300, rowY, { width: 50, align: 'right' });
    doc.text(fmt(item.unitPrice), 360, rowY, { width: 80, align: 'right' });
    doc.text(fmt(item.total), 450, rowY, { width: 85, align: 'right' });
    rowY += 22;
  });

  // Line
  doc.strokeColor('#e5e7eb').lineWidth(1).moveTo(50, rowY + 5).lineTo(545, rowY + 5).stroke();

  // Totals
  const totalsX = 380;
  rowY += 15;
  doc.fillColor('#666666').font('Helvetica').fontSize(9);
  doc.text('Subtotal:', totalsX, rowY); doc.text(fmt(invoice.subtotal), 450, rowY, { width: 85, align: 'right' });
  rowY += 18;
  doc.text(`Tax (${Number(invoice.taxRate)}%):`, totalsX, rowY); doc.text(fmt(invoice.taxAmount), 450, rowY, { width: 85, align: 'right' });
  rowY += 18;
  doc.strokeColor('#e5e7eb').lineWidth(1).moveTo(totalsX, rowY).lineTo(545, rowY).stroke();
  rowY += 8;
  doc.fillColor('#000000').font('Helvetica-Bold').fontSize(12);
  doc.text('Total:', totalsX, rowY); doc.text(fmt(invoice.total), 450, rowY, { width: 85, align: 'right' });

  // Notes
  if (invoice.notes) {
    rowY += 40;
    doc.fillColor('#000000').font('Helvetica-Bold').fontSize(9).text('Notes:', 50, rowY);
    doc.font('Helvetica').fillColor('#666666').fontSize(9).text(invoice.notes, 50, rowY + 15, { width: 400 });
  }

  // Footer
  doc.fillColor('#999999').font('Helvetica').fontSize(8);
  doc.text('Generated by BookFlow', 50, 770, { align: 'center', width: 495 });

  doc.end();
  return stream;
}
